### ISSUE TITLE
import Whatsapp from "@noamalffasy/js-whatsapp";

### ISSUE THREAD

**Issue by ikheeteric** [noamalffasy/js-whatsapp#1]
how to fix this i got in myfile just

import Whatsapp from "@noamalffasy/js-whatsapp";

const wap = new Whatsapp();

wap.sendTextMessage("[text to send]", "[jid]");

**Comment by csgt** [comment]
The ECM syntax is not supported out of the box. You have several options to get this to work.  What I used is an npm package called esm

`npm install -s esm`

and afterwards, running your code using:

`node -r esm index.js`

**Comment by noamalffasy** [comment]
I’m sorry for not responding.

Perhaps the instructions weren’t clear enough, you just need to replace anything between the `[` and `]` (including them) with what’s specified. 

The explanation for what they mean is just above them.

I’m not familiar with the specified library but it’s definitely not needed.
